name: Chatbot App

on:  
    push:    
        branches: [ "main" ]  
    pull_request:    
        branches: [ "main" ]  
    workflow_dispatch:

jobs:  
    build-and-test:    
      runs-on: ubuntu-latest    
    
      steps:      
        - name: Checkout repository        
          uses: actions/checkout@v4  

        - name: Cache pip        
          uses: actions/cache@v3        
          with:          
            path: ~/.cache/pip          
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}          
            restore-keys: | 
                ${{ runner.os }}-pip-      
                
        - name: Set up Python        
          uses: actions/setup-python@v5        
          with:          
                python-version: "3.11"      
                
        - name: Install dependencies        
          run: |          
            python -m pip install --upgrade pip          
            pip install -r requirements.txt          
            
        - name: Run tests        
          env:          
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}          
            API_MONGO: ${{ secrets.API_MONGO }}          
            EMAIL_ADMIN: ${{ secrets.EMAIL_ADMIN }}          
            EMAIL_PASS: ${{ secrets.EMAIL_PASS }}        
          run: |          
            pytest tests/     
            
        - name: Log in to Docker Hub        
          uses: docker/login-action@v2       
          with:          
            username: ${{ secrets.DOCKER_USERNAME }}          
            password: ${{ secrets.DOCKER_PASSWORD }}      
            
        - name: Build and push Docker image        
          run: |          
            docker build -t ${{ secrets.DOCKER_USERNAME }}/chatbot-app:latest .          
            docker push ${{ secrets.DOCKER_USERNAME }}/chatbot-app:latest      
            
        - name: Trigger deploy on Render (Image-backed)        
          run: |
            curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
